doctrine:
    dbal:
        default_connection: main
        connections:
            main:
                url: '%env(DATABASE_URL)%'
                server_version: '%env(int:DATABASE_VERSION)%'

            tenant:
                driver: '%env(TENANT_DATABASE_DRIVER)%'
                server_version: '%env(int:TENANT_DATABASE_VERSION)%'
                charset: utf8
                wrapper_class: App\Multitenancy\Doctrine\DBAL\TenantConnection

    orm:
        default_entity_manager: default
        
        auto_generate_proxy_classes: "%kernel.debug%"
        
        entity_managers:
            
            main:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false # disabled so we can assign entities to our own connections
                connection: main
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Multitenancy/Entity/Main'
                        prefix: 'App\Multitenancy\Entity\Main'
                        alias: Main

            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true # disabled so we can assign entities to our own connections
                connection: tenant
                mappings:
                    Tenant:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
