doctrine:
  dbal:
    #postgres://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME?server_version=10
    url: '%env(resolve:DATABASE_URL)%'
    #url: '%database_driver%://%database_user%:%database_password%@%database_host%/%database_name%?server_version=10'
    charset: UTF8

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      string_functions:
        FORMIO_JSON_FIELD: AppBundle\FormIO\FormIOJsonFieldParser
        JSON_FIELD: AppBundle\Doctrine\JsonFieldParser
