# See full configuration at https://github.com/bestit/flagception-bundle
flagception:
  # Your Features (optional you left it empty)
  features:
    # Feature name as key
    feature_new_outdatedbrowser:
      # Default flag if inactive or active (default: false)
      default: true
      env: FEATURE_NEW_OUTDATED_BROWSER
    feature_application_detail:
      default: true
      env: FEATURE_APPLICATION_DETAIL
    feature_calendar_type:
      default: true
      env: FEATURE_CALENDAR_TYPE
    feature_analytics:
      default: false
      env: FEATURE_ANALYTICS
    feature_service_identifier_readonly:
      default: true
      env: FEATURE_SERVICE_IDENTIFIER_READONLY
