# See full configuration at https://github.com/bestit/flagception-bundle
flagception:
  # Your Features (optional you left it empty)
  features:
    # Feature name as key
    feature_new_outdatedbrowser:
      # Default flag if inactive or active (default: false)
      # You can combine all parameter together. First the default value is checked. If the value is false, the value
      # from env is checked. If this also returns false, the constraints are checked.
      default: true
      env: FEATURE_NEW_OUTDATED_BROWSER
    feature_application_detail:
      default: true
      env: FEATURE_APPLICATION_DETAIL
    feature_calendar_type:
      default: true
      env: FEATURE_CALENDAR_TYPE
    feature_analytics:
      default: false
      env: FEATURE_ANALYTICS
    feature_service_identifier:
      default: false
      env: FEATURE_SERVICE_IDENTIFIER
