# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener:  true
        #formats:
        #    json: true
        #templating_formats:
        #    html: true
    serializer:
        serialize_null: true
    exception:
        enabled: false
    format_listener:
        rules:
            - { path: ^/(.*)/api, prefer_extension: true, fallback_format: json, priorities: ['json']}
            - { path: ^/(.*), prefer_extension: true, fallback_format: html, priorities: ['html', '*/*'] }