nelmio_api_doc:
    documentation:
        info:
            x-api-id: "sdc-api-1-0-0"
            x-audience: "external-public"
            title: "Stanza del Cittadino Rest Api Definition"
            description: ""
            version: "1.0.0"
            contact:
                name: "Opencontent S.c.a.r.l"
                email: "support@opencontent.it"
                url: "https://www.opencontent.it/"
            license:
                name: "GNU General Public License, version 2"
                url: "https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas:
        path_patterns: # an array of regexps
            #- ^/(.*)/api(?!/doc$)
            - ^/(.*)/api/services|applications|subscription-services|calendars|meetings|folders|documents|users(?!/doc$)
