nelmio_api_doc:
  documentation:
    info:
      x-api-id: "sdc-api-2-1-0"
      x-audience: "external-public"
      title: "SDC Api Definition"
      description: ""
      version: "2.1.0"
      contact:
        name: "Opencontent S.c.a.r.l"
        email: "support@opencontent.it"
        url: "https://www.opencontent.it/"
      license:
        name: "GNU General Public License, version 2"
        url: "https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Authorization: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: [ ]
  areas:
    path_patterns: # an array of regexps
      #- ^/%prefix%/api(?!/doc$)
      - ^/%prefix%/api/services|services-groups|applications|subscription-services|subscriptions|calendars|meetings|folders|documents|messages|users(?!/doc$)
