# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
oneup_flysystem:
  #adapters:
  #  default_adapter:
  #    local:
  #      directory: '%kernel.cache_dir%/flysystem'
  #filesystems:
  #  default_filesystem:
  #    adapter: default_adapter
  #    alias: League\Flysystem\Filesystem
  adapters:
    s3_adapter:
      awss3v3:
        client: ocsdc.s3_client
        bucket: "%s3_bucket%"
        prefix: 'uploads'
    local_adapter:
      local:
        directory: '%kernel.root_dir%/../var/uploads'
  filesystems:
    s3_filesystem:
      adapter: s3_adapter
      mount: s3_filesystem
      # optional - defines the default visibility of the filesystem: `public` or `private`(default)
      visibility: private
      alias: s3_filesystem
    local_filesystem:
      adapter: local_adapter
      mount: local_filesystem
      alias: local_filesystem
