vich_uploader:
  db_driver: orm
  storage: flysystem
  mappings:
    allegato:
      #uri_prefix: /pratiche/allegati
      upload_destination: '%upload_destination%' # s3_filesystem, local_filesystem
      directory_namer: ocsdc.allegati.directory_namer
      namer: vich_uploader.namer_uniqid
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
