white_october_breadcrumbs:
  separator: '/'
  separatorClass: 'separator'
  listId: 'breadcrumb'
  listClass: 'breadcrumb pb-0'
  itemClass: 'breadcrumb-item'
  linkRel: ''
  locale: ~ # defaults to null, so the default locale is used
  translation_domain: ~ # defaults to null, so the default domain is used
  viewTemplate: 'Default/breadcrumbs.html.twig'
