version: "3"

services:

  php:
    build:
      context: .
      args:
        wodby_version: 7.3-dev-macos
    environment:
      ENV: DEV
      APP_ENV: dev
    volumes:
      - ./config:/var/www/html/config:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./templates:/var/www/html/templates:rw,cached
      - ./translations:/var/www/html/translations:rw,cached
      - ./migrations:/var/www/html/migrations:rw,cached
      - ./public:/var/www/html/public:rw,cached
      - ./tests:/var/www/html/tests:rw,cached
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist:rw,cached

  #apache:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.apache
  #    args:
  #      php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
  #  volumes:
  #    - ./public:/var/www/html/public:rw

  caddy:
    volumes:
      - ./public:/srv:rw

  pgadmin:
    image: dpage/pgadmin4:6.4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
