version: "3.8"

services:

  php:
    build:
      context: .
      args:
        wodby_version: 7.4-dev-macos
    environment:
      ENV: DEV
      APP_ENV: dev
    volumes:
      - ./config:/var/www/html/config:rw,cached
      - ./data:/var/www/html/data:rw,cached
      - ./compose_conf:/var/www/html/compose_conf:rw,cached
      - ./bin:/var/www/html/bin:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./templates:/var/www/html/templates:rw,cached
      - ./translations:/var/www/html/translations:rw,cached
      - ./migrations:/var/www/html/migrations:rw,cached
      - ./public:/var/www/html/public:rw,cached
      - ./tests:/var/www/html/tests:rw,cached
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist:rw,cached
      - ./composer.json:/var/www/html/composer.json:rw,cached

  cron:
    command: bash -c ""

  #caddy:
  #  volumes:
  #    - ./public:/srv:rw

  mailserver:
    ports:
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4:6.4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
