version: "3"

services:

  php:
    ## Read instructions at https://wodby.com/stacks/php/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV: DEV
    volumes:
      - ./app:/var/www/html/app:delegated
      - ./src:/var/www/html/src:delegated
      - docker-sync:/var/www/html

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    volumes:
      - ./web:/var/www/html/web:cached

  pgweb:
    image: sosedoff/pgweb
    labels:
      - 'traefik.port=8081'
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres

volumes:
  ## Docker-sync for macOS users
  docker-sync:
    external: true
