ARG php_image
FROM ${php_image} as php

FROM caddy:2

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=php /var/www/html/web /srv

#HEALTHCHECK --start-period=2s --interval=30s --timeout=3s \
#        CMD curl --fail localhost/health || exit 1

