# prepare assets for symfony
FROM node:10.15.0 as assets

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY package.json package.json yarn.lock yarn.lock webpack.config.js ./

RUN yarn install

COPY assets ./assets
RUN yarn encore production
RUN ls -l public

FROM composer:1.8.4 as composer

RUN rm -rf /var/www && mkdir /var/www
WORKDIR /var/www

COPY composer.* /var/www/

ARG APP_ENV=prod

RUN set -xe \
    && if [ "$APP_ENV" = "prod" ]; then export ARGS="--no-dev"; fi \
    && composer install --prefer-dist --no-scripts --no-progress --no-suggest --no-interaction $ARGS

COPY . /var/www

RUN composer dump-autoload --classmap-authoritative

FROM wodby/php:7.3-dev-macos-4.12.12

ENV PHP_FPM_USER=wodby
ENV PHP_FPM_GROUP=wodby

WORKDIR /var/www/html

ARG APP_ENV=prod
ARG APP_DEBUG=0

ENV APP_ENV $APP_ENV
ENV APP_DEBUG $APP_DEBUG

COPY --chown=wodby:wodby --from=composer /var/www/vendor /var/www/html/vendor
COPY --from=builder /var/www/html/vendor /var/www/html/vendor
COPY --chown=wodby:wodby --from=assets /home/node/app/public /var/www/html/public

COPY --chown=wodby:wodby ./compose_conf/bin/*.sh ./bin
RUN chmod 755 ./bin/*.sh

#RUN php -d memory_limit=256M bin/console cache:clear
#RUN bin/console assets:install

#COPY compose_conf/php/init*.sh /docker-entrypoint-init.d/

#RUN bin/console cache:warmup

USER wodby
