version: "3"

services:

  php:
    ## Read instructions at https://wodby.com/stacks/php/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV: DEV
      shibb_pat_attribute_codicefiscale: RLDLCU77T05G224F
      shibb_pat_attribute_cognome: Realdi
      shibb_pat_attribute_emailaddress: lr@opencontent.it
      shibb_pat_attribute_nome: Luca
      shibb_pat_attribute_telefono: 123
      shibb_pat_attribute_cellulare: 456
      shibb_pat_attribute_indirizzoresidenza: Via il male dal mondo, 15
      shibb_pat_attribute_capresidenza: 00100
      shibb_pat_attribute_cittaresidenza: Roma
      shibb_pat_attribute_provinciaresidenza: Roma
      shibb_pat_attribute_statoresidenza: Tristalia,
      shibb_pat_attribute_x509certificate_issuerdn: FAKE_issuerdn
      shibb_pat_attribute_x509certificate_subjectdn: FAKE_subjectdn
      shibb_pat_attribute_x509certificate_base64: DQpSZXN1bHQgZ29lcyBoZXJlLi4uDQpCYXNlNjQNCg0KQmFzZTY0IGlzIGEgZ2VuZXJpYyB0ZXJtIGZvciBhIG51bWJlciBvZiBzaW1pbGFyIGVuY29kaW5nIHNjaGVtZXMgdGhhdCBlbmNvZGUgYmluYXJ5IGRhdGEgYnkgdHJlYXRpbmcgaXQgbnVtZXJpY2FsbHkgYW5kIHRyYW5zbGF0aW5nIGl0IGludG8gYSBiYXNlIDY0IHJlcHJlc2VudGF0aW9uLiBUaGUgQmFzZTY0IHRlcm0gb3JpZ2luYXRlcyBmcm9tIGEgc3BlY2lmaWMgTUlNRSBjb250ZW50IHRyYW5zZmVyIGVuY29kaW5nLg==
    volumes:
      - ./app:/var/www/html/app:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./web:/var/www/html/web:rw,cached
      - ./var/uploads:/var/www/html/var/uploads:rw,cached

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    volumes:
      - ./web:/var/www/html/web:ro

  pgweb:
    image: sosedoff/pgweb
    labels:
      - 'traefik.port=8081'
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres

  gotemberg:
    image: thecodingmachine/gotenberg:6
    restart: unless-stopped
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 5s
    environment:
      LOG_LEVEL: INFO
      # DEFAULT_LISTEN_PORT: 3000
      # DISABLE_GOOGLE_CHROME: 0
      # DEFAULT_GOOGLE_CHROME_RPCC_BUFFER_SIZE: "1048576" #1Mb, max 100Mb
      DISABLE_UNOCONV: 1
      #DEFAULT_WAIT_TIMEOUT: 5
      #MAXIMUM_WAIT_TIMEOUT: 30
      #DEFAULT_WEBHOOK_URL_TIMEOUT: "2.5"
      #MAXIMUM_WEBHOOK_URL_TIMEOUT: "2.5"
      #MAXIMUM_WAIT_DELAY: "2.5"

  #volumes:
  ## Docker-sync for macOS users
  #docker-sync:
  #  external: true
