version: "3"

services:

  php:
    ## Read instructions at https://wodby.com/stacks/php/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    build:
      context: .
      args:
        wodby_version: 7.3-dev-macos
    environment:
      ENV: DEV
      SYMFONY_ENV: dev
    volumes:
      - ./app:/var/www/html/app:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./web:/var/www/html/web:rw,cached
      - ./var/uploads:/var/www/html/var/uploads:rw,cached

  #apache:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.apache
  #    args:
  #      php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
  #  volumes:
  #    - ./web:/var/www/html/web:rw

  caddy:
    volumes:
      - ./web:/srv:rw


  # Enable only to test metrics export in PHP container
  #redis:
  #  image: wodby/redis:5-3.7.6
  #  environment:
  #    REDIS_PASSWORD: $METRICS_REDIS_PASSWORD

# Enable to have a postgres web interface
#  pgweb:
#    image: sosedoff/pgweb
#    labels:
#      traefik.enable: true
#      #traefik.http.services.pgweb.loadbalancer.server.port: 8081
#      traefik.http.routers.pgweb-http.rule: 'Host(`pgweb.localtest.me`)'
#      traefik.http.routers.pgweb-http.entrypoints: web
#    environment:
#      - DATABASE_URL=postgres://${DB_USER:-sdc}:${DB_PASSWORD:-sdc}@postgres:5432/${DB_NAME:-sdc_bugliano}?sslmode=disable
#    depends_on:
#      - postgres

