version: "3.7"

services:

  postgres:
    image: wodby/postgres:${POSTGRES_TAG:-10-1.6.0}
    stop_grace_period: 30s
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD:-sdc}
      POSTGRES_DB: sdc_multi
      POSTGRES_USER: ${DB_USER:-sdc}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --user sdc --dbname sdc_multi"]
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
      #- ./compose_conf/postgres:/docker-entrypoint-initdb.d
      #- pgdata:/var/lib/postgresql/data/pgdata

  php:
    image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    build: .
    stop_grace_period: 90s
    environment:
      PHP_FPM_CLEAR_ENV: 'no'
      ENV: ${ENV:-DEV}
      SYMFONY_ENV: ${SYMFONY_ENV:-dev}
      ENABLE_MIGRATIONS: 'true'
      ENABLE_INSTANCE_CONFIG: 'true'
      PREFIX: ${PREFIX:-}
      DB_DRIVER: ${DB_DRIVER:-pdo_pgsql}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-sdc_multi}
      DB_USER: ${DB_USER:-sdc}
      DB_PASSWORD: ${DB_PASSWORD:-sdc}
      MAILER_TRANSPORT: ${MAILER_TRANSPORT:-sendmail}
      MAILER_HOST: ${MAILER_HOST:-127.0.0.1}
      MAILER_USER: ${MAILER_USER:-null}
      MAILER_PASSWORD: ${MAILER_PASSWORD:-null}
      PEC_MAILER_TRANSPORT: ${PEC_MAILER_TRANSPORT:-smtp}
      PEC_MAILER_HOST: ${PEC_MAILER_HOST:-smtp.pec.net}
      PEC_MAILER_PORT: ${PEC_MAILER_PORT:-465}
      PEC_MAILER_USER: ${PEC_MAILER_USER:-stanzadelcittadino@pec.net}
      PEC_MAILER_PASSWORD: ${PEC_MAILER_PASSWORD:-WhoKnows}
      PEC_DELIVERY_ADDRESS: ${PEC_DELIVERY_ADDRESS-:stanzadelcittadino@pec.net}
      SECRET: ${SECRET:-ThisTokenIsNotSoSecretChangeIt}
      DEFAULT_FROM_EMAIL_ADDRESS: ${DEFAULT_FROM_EMAIL_ADDRESS:-sdc@opencontent.it}
      WKHTMLBINARY: ${WKHTMLBINARY:-wkhtmltopdf}
      WKHTMLTOPDF_SERVICE: ${WKHTMLTOPDF_SERVICE:-gotemberg}
      EZ_PASSWORD: ${EZ_PASSWORD:-ez}
      PITRE_ADAPTER_URL: ${PITRE_ADAPTER_URL:-http://localhost:8080/}
      #HEADER_TOP_TITLE: $HEADER_TOP_TITLE
      #HEADER_TOP_LINK: $HEADER_TOP_LINK
      #FOOTER_CREDITS: $FOOTER_CREDITS
      #OCSDC_SCHEME: $OCSDC_SCHEME
      #OCSDC_HOST: $OCSDC_HOST
      GISCOM_PASSWORD: ${GISCOM_PASSWORD:-giscom}
      GISCOM_ADAPTER_URL: ${GISCOM_ADAPTER_URL:-https://www.giscom.cloud/WebAPI/}
      GISCOM_ADAPTER_USERNAME: ${GISCOM_ADAPTER_USERNAME:-pippo}
      GISCOM_ADAPTER_PASSWORD: ${GISCOM_ADAPTER_PASSWORD:-passw}
      LOGS_PATH: ${LOGS_PATH:-php://stderr}
      MYPAY_ADAPTER_URL: ${MYPAY_ADAPTER_URL:-http://localhost:3000}
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_APCU_ENABLED: 0
      PHP_OPCACHE_ENABLE: 0
      FORMSERVER_PRIVATE_URL: ${FORMSERVER_PRIVATE_URL:-http://formserver:8000}
      FORMSERVER_PUBLIC_URL: ${FORMSERVER_PUBLIC_URL:-http://formserver.localtest.me:8000}
      FORMSERVER_ADMIN_URL: ${FORMSERVER_ADMIN_URL:-http://formserver.localtest.me:8000}
      RECAPTCHA_KEY: ${RECAPTCHA_KEY:-key}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET:-secret}
      SENTRY_DSN: ${SENTRY_DSN:-}
      PHP_DATE_TIMEZONE: 'Europe/Rome'
      PASSWORD_LIFE_TIME: ${PASSWORD_LIFE_TIME:-999999}
      HASH_VALIDITY: ${HASH_VALIDITY:-3}
      TOKEN_TTL: ${TOKEN_TTL:-3600}
      LOGIN_ROUTE: ${LOGIN_ROUTE:-login_open}
      SINGLE_LOGOUT_URL: '/Shibboleth.sso/Logout'
      IO_API_URL: ${IO_API_URL:-https://api.io.italia.it/api/v1}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE:-3600}
      METRICS_TYPE: ${METRICS_TYPE:-in_memory}
      METRICS_REDIS_HOST: ${METRICS_REDIS_HOST:-redis}
      METRICS_REDIS_PORT: ${METRICS_REDIS_PORT:-6379}
      METRICS_REDIS_PASSWORD: ${METRICS_REDIS_PASSWORD:-}
      UPLOAD_DESTINATION: ${UPLOAD_DESTINATION:-local_filesystem}
      S3_REGION: ${S3_REGION:-}
      S3_KEY: ${S3_KEY:-}
      S3_SECRET: ${S3_SECRET:-}
      S3_BUCKET: ${S3_BUCKET:-}
      KAFKA_URL: ${KAFKA_URL:-}

      # Your Queue-it customer ID
      #QUEUEIT_CUSTOMER_ID: 'xxx'
      # Your 72 char secret key as specified in Go Queue-it self-service platform
      #QUEUEIT_SECRET: 'xxx'
      # Absolute path of Queue-it configuration json file @see https://github.com/queueit/KnownUser.V3.PHP/blob/master/Documentation/README.md
      #QUEUEIT_CONFIG_FILE: '/var/www/html/opencontent_knownuser_integration_config.json'

      # In assenza di una vera autenticazione basata su SPID si può simulare
      # un login di un utente con le seguenti variabili d'ambiente:
      #shibb_pat_attribute_codicefiscale: ABCDEF00A11Z456X
      #shibb_pat_attribute_cognome: Coliandro
      #shibb_pat_attribute_nome: Vittorino
      #shibb_pat_attribute_sesso: M
      #shibb_pat_attribute_emailaddress: info@comune.bugliano.pi.it
      #shibb_pat_attribute_datanascita: 1/9/1976
      #shibb_pat_attribute_luogonascita: Ponsacco
      #shibb_pat_attribute_provincianascita: PI

      #shibb_pat_attribute_telefono: 003912378945
      #shibb_pat_attribute_cellulare: 333 444 666 99
      #shibb_pat_attribute_indirizzoresidenza: Via Gramsci, 1
      #shibb_pat_attribute_capresidenza: 56056
      #shibb_pat_attribute_cittaresidenza: Bugliano
      #shibb_pat_attribute_provinciaresidenza: PI
      #shibb_pat_attribute_statoresidenza: Italia
      #shibb_pat_attribute_spidcode: 123456789
      #shibb_pat_attribute_x509certificate_issuerdn: FAKE_issuerdn
      #shibb_pat_attribute_x509certificate_subjectdn: FAKE_subjectdn
      #shibb_pat_attribute_x509certificate_base64: "DQpSZXN1bHQgZ29lcyBoZXJlLi4uDQpCYXNlNjQNCg0KQmFzZTY0IGlzIGEgZ2VuZXJpYyB0ZXJtIGZvciBhIG51bWJlciBvZiBzaW1pbGFyIGVuY29kaW5nIHNjaGVtZXMgdGhhdCBlbmNvZGUgYmluYXJ5IGRhdGEgYnkgdHJlYXRpbmcgaXQgbnVtZXJpY2FsbHkgYW5kIHRyYW5zbGF0aW5nIGl0IGludG8gYSBiYXNlIDY0IHJlcHJlc2VudGF0aW9uLiBUaGUgQmFzZTY0IHRlcm0gb3JpZ2luYXRlcyBmcm9tIGEgc3BlY2lmaWMgTUlNRSBjb250ZW50IHRyYW5zZmVyIGVuY29kaW5nLg=="
      #shibb_Shib-Session-ID: abc123abc123abc123abc123abc123abc123abc123
      #shibb_Shib-Session-Index: abc123abc123abc123abc123abc123abc123abc123
      #shibb_Shib-Authentication-Instant: 2000-01-01T00-00Z

    volumes:
      - "uploads:/var/www/html/var/uploads"

  caddy:
    image: registry.gitlab.com/opencontent/stanzadelcittadino/caddy:master
    #volumes:
    #  - "uploads:/srv/uploads"
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile.caddy
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    labels:
      traefik.enable: true
      traefik.http.services.caddy.loadbalancer.server.port: 80

      traefik.http.middlewares.spid-auth.forwardauth.address: http://auth.localtest.me
      traefik.http.middlewares.spid-auth.forwardauth.authResponseHeaders: "X-Forwarded-User,X-Forwarded-User-Provider,X-Forwarded-User-registeredOffice,X-Forwarded-User-spidCode,X-Forwarded-User-name,X-Forwarded-User-companyName,X-Forwarded-User-ivaCode,X-Forwarded-User-countyOfBirth,X-Forwarded-User-idCard,X-Forwarded-User-gender,X-Forwarded-User-dateOfBirth,X-Forwarded-User-placeOfBirth,X-Forwarded-User-familyName,X-Forwarded-User-fiscalNumber,X-Forwarded-User-digitalAddress,X-Forwarded-User-mobilePhone,X-Forwarded-User-expirationDate,X-Forwarded-User-email,X-Forwarded-User-address,X-Forwarded-User-Session,X-Forwarded-User-Spid-Level,X-Forwarded-User-Spid-Idp"
      traefik.http.middlewares.spid-auth.forwardauth.trustForwardHeader: true

      traefik.http.routers.caddy-auth.entrypoints: web
      traefik.http.routers.caddy-auth.rule: "Host(`stanzadelcittadino.localtest.me`) && Path(`/{tenant:[^/]+}/auth/login-open`)"
      traefik.http.routers.caddy-auth.middlewares: "spid-auth"

      traefik.http.routers.caddy.entrypoints: web
      traefik.http.routers.caddy.rule: 'Host(`stanzadelcittadino.localtest.me`)'

  apache:
    image: registry.gitlab.com/opencontent/stanzadelcittadino/apache:master
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/web
      WEB_PHP_SOCKET: php:9000
      ORGANIZATION: ${ORGANIZATION:-Comune di Qui}
      SERVER_NAME: ${SERVER_NAME:-stanzadelcittadino.localtest.me}
      ENTITY_ID: ${ENTITY_ID:-stanzadelcittadino.localtest.me}
      PROJECT_BASE_URL: ${PROJECT_BASE_URL:-stanzadelcittadino.localtest.me}
    ports:
      - "443:443"
    labels:
      traefik.enable: true
      traefik.http.routers.apache.entrypoints: web
      traefik.http.routers.apache.rule: 'Host(`stanzadelcittadino.localtest.me`) && Path(`/{tenant:[^/]+}/auth/login-pat`)'

  traefik:
    image: 'traefik:2.0'
    restart: unless-stopped
    #command: -c /dev/null --web --docker --logLevel=DEBUG --docker.domain=localtest.me
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - '--entryPoints.web.forwardedHeaders.insecure'
    labels:
      traefik.http.routers.traefik.rule: 'Host(`localtest.me`)'
    ports:
      - '80:80'
    #  - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:4.2.2
    restart: unless-stopped
    #volumes:
      #- 'mongo:/data/db'
  #    - './compose_conf/mongo/dump/:/dump/'
  #    - './compose_conf/mongo/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  formserver:
    image: registry.gitlab.com/opencontent/formmanagerserver:1.0.11
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      DB_URL: mongodb://mongo:27017/formmanager
    depends_on:
      - mongo
    labels:
      traefik.enable: true
      traefik.http.services.formserver.loadbalancer.server.port: 8000
      traefik.http.routers.formserver.entrypoints: web
      traefik.http.routers.formserver.rule: 'Host(`formserver.localtest.me`)'

  gotemberg:
    image: thecodingmachine/gotenberg:6
    restart: unless-stopped
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 5s
    environment:
      LOG_LEVEL: INFO
      # DEFAULT_LISTEN_PORT: 3000
      # DISABLE_GOOGLE_CHROME: 0
      # DEFAULT_GOOGLE_CHROME_RPCC_BUFFER_SIZE: "1048576" #1Mb, max 100Mb
      DISABLE_UNOCONV: 1
      #DEFAULT_WAIT_TIMEOUT: 5
      #MAXIMUM_WAIT_TIMEOUT: 30
      #DEFAULT_WEBHOOK_URL_TIMEOUT: "2.5"
      #MAXIMUM_WEBHOOK_URL_TIMEOUT: "2.5"
      MAXIMUM_WAIT_DELAY: "30"

  openlogin:
    image: registry.gitlab.com/opencontent/traefik-spid-auth:1.1.0
    restart: unless-stopped
    environment:
      SYNFONY_ENV: dev
      ENABLE_PROVIDERS: spid
      SP_ENTITYID: 'http://auth.localtest.me/'
      SP_SINGLELOGOUT: 'http://auth.localtest.me/slo'
      SP_ACS: 'http://auth.localtest.me/acs'
      SP_ORG_NAME: 'Ambiente di sviluppo di OpenLogin'
      SP_ORG_DISPLAY_NAME: 'Opencontent Scarl'
      SP_CONTACT_IPA_CODE: 'opncnt_1'
      SP_CONTACT_EMAIL: 'info@opencontent.it'
      SP_CONTACT_PHONE: '00390461917437'
      SPID_LEVEL: 2
      TEST_SPID_IDP: 'enabled'
      TEST_SPID_IDP_ID: 'http://spid.localtest.me/'
      TEST_SPID_IDP_NAME: 'Test IdP'
      TEST_SPID_IDP_METADATA_NUMBER: 10
      #facebook
      OAUTH_FACEBOOK_CLIENT_ID: ''
      OAUTH_FACEBOOK_CLIENT_SECRET: ''
      #github
      OAUTH_GITHUB_CLIENT_ID: ''
      OAUTH_GITHUB_CLIENT_SECRET: ''
      #google
      OAUTH_GOOGLE_CLIENT_ID: ''
      OAUTH_GOOGLE_CLIENT_SECRET: ''
      #instagram
      OAUTH_INSTAGRAM_CLIENT_ID: ''
      OAUTH_INSTAGRAM_CLIENT_SECRET: ''
      COOKIE_LIFETIME_SECONDS: 20
    labels:
      traefik.enable: true
      traefik.http.services.openlogin.loadbalancer.server.port: 2015
      traefik.http.routers.openlogin-http.rule: Host(`auth.localtest.me`)
      traefik.http.routers.openlogin-http.entrypoints: web
    volumes:
      #- ./openlogin/var:/srv/app/var:rw
      - ./openlogin/spid:/srv/app/spid:ro

  # identity provider di prova
  idp:
    image: italia/spid-testenv2
    restart: unless-stopped
    depends_on:
      - openlogin
    volumes:
      - ./openlogin/idp:/app/conf
    environment:
      FLASK_ENV: development
    labels:
      traefik.enable: true
      traefik.http.services.idp.loadbalancer.server.port: 80
      traefik.http.routers.idp-http.rule: 'Host(`spid.localtest.me`)'
      traefik.http.routers.idp-http.entrypoints: web
    links:
      - "openlogin:auth.localtest.me"

  redis:
    image: wodby/redis:5-3.7.6
    environment:
      REDIS_PASSWORD: $METRICS_REDIS_PASSWORD

  pgweb:
    image: sosedoff/pgweb
    labels:
      traefik.enable: true
      #traefik.http.services.pgweb.loadbalancer.server.port: 80
      traefik.http.routers.pgweb-http.rule: 'Host(`pgweb.localtest.me`)'
      traefik.http.routers.pgweb-http.entrypoints: web
    environment:
      - DATABASE_URL=postgres://${DB_USER:-sdc}:${DB_PASSWORD:-sdc}@postgres:5432/${DB_NAME:-sdc_bugliano}?sslmode=disable
    depends_on:
      - postgres

volumes:
#  pgdata:
  uploads:
  mongo:
