version: "3"

services:

  php:
    ## Read instructions at https://wodby.com/stacks/php/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV: DEV
      SYMFONY_ENV: dev
      LOGIN_ROUTE: login_pat
      #FEATURE_NEW_OUTDATED_BROWSER: 'true'
      FEATURE_APPLICATION_DETAIL: 'true'
      shibb_pat_attribute_codicefiscale: RSSMRA80A01H501U
      shibb_pat_attribute_cognome: Rossi
      shibb_pat_attribute_emailaddress: mario.rossi@sdc.it
      shibb_pat_attribute_nome: Mario
      shibb_pat_attribute_sesso: M
      shibb_pat_attribute_datanascita: 01/01/1980
      shibb_pat_attribute_luogonascita: 00100
      shibb_pat_attribute_provincianascita: AQ
      shibb_pat_attribute_telefono: 3331234567
      shibb_pat_attribute_cellulare: 3331234567
      shibb_pat_attribute_indirizzoresidenza: Via Roma, 1
      shibb_pat_attribute_capresidenza: 00100
      shibb_pat_attribute_cittaresidenza: Roma
      shibb_pat_attribute_provinciaresidenza: Roma
      shibb_pat_attribute_statoresidenza: Italia,
      shibb_pat_attribute_spid_code: REGIISXXR42317
      shibb_Shib-Session-ID: session_id
      shibb_Shib-Session-Index: session_index
      shibb_Shib-Authentication-Instant: auth_instant
      shibb_pat_attribute_x509certificate_issuerdn: FAKE_issuerdn
      shibb_pat_attribute_x509certificate_subjectdn: FAKE_subjectdn
      shibb_pat_attribute_x509certificate_base64: DQpSZXN1bHQgZ29lcyBoZXJlLi4uDQpCYXNlNjQNCg0KQmFzZTY0IGlzIGEgZ2VuZXJpYyB0ZXJtIGZvciBhIG51bWJlciBvZiBzaW1pbGFyIGVuY29kaW5nIHNjaGVtZXMgdGhhdCBlbmNvZGUgYmluYXJ5IGRhdGEgYnkgdHJlYXRpbmcgaXQgbnVtZXJpY2FsbHkgYW5kIHRyYW5zbGF0aW5nIGl0IGludG8gYSBiYXNlIDY0IHJlcHJlc2VudGF0aW9uLiBUaGUgQmFzZTY0IHRlcm0gb3JpZ2luYXRlcyBmcm9tIGEgc3BlY2lmaWMgTUlNRSBjb250ZW50IHRyYW5zZmVyIGVuY29kaW5nLg==
    volumes:
      - ./app:/var/www/html/app:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./web:/var/www/html/web:rw,cached
      - ./var/uploads:/var/www/html/var/uploads:rw,cached

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    volumes:
      - ./web:/var/www/html/web:rw

  caddy:
    volumes:
      - ./web:/srv:rw
