version: "3"

services:

  php:
    ## Read instructions at https://wodby.com/stacks/php/docs/local/xdebug/
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ENV: DEV
      APP_DEBUG: 'true'
      shibb_pat_attribute_codicefiscale: RLDLCU77T05G224F
      shibb_pat_attribute_cognome: Realdi
      shibb_pat_attribute_emailaddress: lr@opencontent.it
      shibb_pat_attribute_datanascita: 01/01/1980
      shibb_pat_attribute_nome: Luca
      shibb_pat_attribute_telefono: 123
      shibb_pat_attribute_cellulare: 456
      shibb_pat_attribute_indirizzoresidenza: Via il male dal mondo, 15
      shibb_pat_attribute_capresidenza: 00100
      shibb_pat_attribute_cittaresidenza: Roma
      shibb_pat_attribute_provinciaresidenza: Roma
      shibb_pat_attribute_statoresidenza: Italia
      shibb_pat_attribute_x509certificate_issuerdn: FAKE_issuerdn
      shibb_pat_attribute_x509certificate_subjectdn: FAKE_subjectdn
      shibb_pat_attribute_x509certificate_base64: DQpSZXN1bHQgZ29lcyBoZXJlLi4uDQpCYXNlNjQNCg0KQmFzZTY0IGlzIGEgZ2VuZXJpYyB0ZXJtIGZvciBhIG51bWJlciBvZiBzaW1pbGFyIGVuY29kaW5nIHNjaGVtZXMgdGhhdCBlbmNvZGUgYmluYXJ5IGRhdGEgYnkgdHJlYXRpbmcgaXQgbnVtZXJpY2FsbHkgYW5kIHRyYW5zbGF0aW5nIGl0IGludG8gYSBiYXNlIDY0IHJlcHJlc2VudGF0aW9uLiBUaGUgQmFzZTY0IHRlcm0gb3JpZ2luYXRlcyBmcm9tIGEgc3BlY2lmaWMgTUlNRSBjb250ZW50IHRyYW5zZmVyIGVuY29kaW5nLg==
    volumes:
      - ./config:/var/www/html/config:rw,cached
      - ./bin:/var/www/html/bin:rw,cached
      - ./src:/var/www/html/src:rw,cached
      - ./assets:/var/www/html/assets:rw,cached
      - ./migrations:/var/www/html/migrations:rw,cached
      - ./templates:/var/www/html/templates:rw,cached
      - ./translations:/var/www/html/translations:rw,cached
      #- ./web:/var/www/html/web:rw,cached
      - ./public:/var/www/html/public:rw,cached
      - ./var/uploads:/var/www/html/var/uploads:rw,cached

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
      args:
        php_image: registry.gitlab.com/opencontent/stanzadelcittadino/app:master
    volumes:
      #- ./web:/var/www/html/web:rw
      - ./public:/var/www/html/public:rw

  pgweb:
    image: sosedoff/pgweb
    labels:
      - 'traefik.port=8081'
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres

  #volumes:
  ## Docker-sync for macOS users
  #docker-sync:
  #  external: true
