version: "3.8"

services:

  php:
    environment:
      KAFKA_URL: krakend:8080

  zookeeper:
    image: wurstmeister/zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MESSAGE_MAX_BYTES: 2147483647
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483647
      #KAFKA_HEAP_OPTS: '-Xmx2G -Xms2G'
      #KAFKA_JVM_PERFORMANCE_OPTS: '-Xmx2G -Xms2G'

  krakend:
    image: devopsfaith/krakend:1.3
    volumes:
      - ./compose_conf/kafka/krakend.json:/etc/krakend.json
    command: run -c /etc/krakend.json -d
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092

  kowl:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'default'
      traefik.http.services.kowl.loadbalancer.server.port: 8080
      traefik.http.routers.kowl.rule: 'Host(`kowl.localtest.me`)'

