
fos_user:
    from_email:
      address: 'no.reply@stanzadelcittadino.it'
      sender_name: 'Stanza del cittadino'
    db_driver: orm
    firewall_name: operatori
    user_class: AppBundle\Entity\User
