guzzle:
  clients:
    protocollo_cct:
      base_url: '%pitre_adapter_url%'
      options:
        timeout: 120
      headers:
        Accept: 'application/json'
    comunweb:
      options:
        timeout: 3
      headers:
        Accept: 'application/json'
    mypay:
      base_url: '%mypay_adapter_url%'
    giscom:
      base_url: '%giscom_adapter_url%'
      options:
        timeout: 120
        verify: false
        auth:
          - '%giscom_adapter_username%' # login
          - '%giscom_adapter_password%' # password
      headers:
        Accept: 'application/json'
