vich_uploader:
  db_driver: orm
  mappings:
    allegato:
      uri_prefix:         /pratiche/allegati
      upload_destination: %kernel.root_dir%/../web/pratiche/allegati
      #TODO: Il namer andrà cambiato con un service per metterli per fascicolo
      namer:              vich_uploader.namer_uniqid
      inject_on_load:     true
      delete_on_update:   true
      delete_on_remove:   true
