imports:
  - { resource: common/monolog_dev.yml }
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: app.yml }
  - { resource: bundles/ }
  - { resource: config.yml }

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

swiftmailer:
  delivery_address: sdc_dev@opencontent.it

services:
  ocsdc.protocollo.handler: "@ocsdc.protocollo.handlers.dummy"
