parameters:
    prefix: '%env(PREFIX)%'
    database_driver: '%env(DB_DRIVER)%'
    database_host: '%env(DB_HOST)%'
    database_port: '%env(DB_PORT)%'
    database_name: '%env(DB_NAME)%'
    database_user: '%env(DB_USER)%'
    database_password: '%env(DB_PASSWORD)%'
    mailer_transport: '%env(MAILER_TRANSPORT)%'
    mailer_host: '%env(MAILER_HOST)%'
    mailer_port: '%env(MAILER_PORT)%'
    mailer_user: '%env(MAILER_USER)%'
    mailer_password: '%env(MAILER_PASSWORD)%'
    mailer_encription: 'tls'
    secret: '%env(SECRET)%'
    default_from_email_address: '%env(DEFAULT_FROM_EMAIL_ADDRESS)%'
    wkhtmlbinary: '%env(WKHTMLBINARY)%'
    wkhtmltopdf_service: '%env(WKHTMLTOPDF_SERVICE)%'
    ez_password: '%env(EZ_PASSWORD)%'
    pitre_adapter_url: '%env(PITRE_ADAPTER_URL)%'
    messages_backend_url: 'http://localhost:3000/'
    header_top_title: '%env(HEADER_TOP_TITLE)%'
    header_top_link: '%env(HEADER_TOP_LINK)%'
    footer_credits: '%env(FOOTER_CREDITS)%'
    ocsdc_iter_duration_start_status: 3
    ocsdc_iter_duration_end_statuses:
        - 10
        - 100
    ocsdc_default_date_format: 'd-m-Y'
    ocsdc_default_datetime_format: 'd-m-Y H:i'
    ocsdc_default_time_format: 'H:i'
    ocsdc_scheme: '%env(OCSDC_SCHEME)%'
    ocsdc_host: '%env(OCSDC_HOST)%'
    giscom_password: '%env(GISCOM_PASSWORD)%'
    giscom_adapter_url: '%env(GISCOM_ADAPTER_URL)%'
    giscom_adapter_username: '%env(GISCOM_ADAPTER_USERNAME)%'
    giscom_adapter_password: '%env(GISCOM_ADAPTER_PASSWORD)%'
    generate_p7m_thumbnail: true
    gsbinary: gs
    messages_enabled: false
    ocsdc_default_moment_datetime_format: 'DD-MM-YYYY HH:mm'
    mypay_adapter_url: '%env(MYPAY_ADAPTER_URL)%'
    slack_logs_webhook_url: 'http://slack.com'
    ocsdc_slim_datetime_format: 'd/m/y H:i'
    PasswordLifeTime: '%env(PASSWORD_LIFE_TIME)%' #365
    InactiveUserLifeTime: '%env(INACTIVE_USER_LIFE_TIME)%' #545
    logs_formatter: 'monolog.formatter.line'
    logs_path: '%env(LOGS_PATH)%'
    formserver_private_url: '%env(FORMSERVER_PRIVATE_URL)%'
    formserver_public_url: '%env(FORMSERVER_PUBLIC_URL)%'
    hash_validity: '%env(HASH_VALIDITY)%'
    allowed_extensions:
      - doc: application/msword
      - docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - odt: application/vnd.oasis.opendocument.text
      - pdf: application/pdf
      - txt: text/plain
      - jpeg: image/jpeg
      - jpg: image/jpeg
      - png: image/png
    #Default fallback if env not set
    env(PREFIX): ''
    env(DB_DRIVER): 'pdo_pgsql'
    env(DB_HOST): 'postgres'
    env(DB_PORT): '5432'
    env(DB_NAME): 'sdc_multi'
    env(DB_USER): 'sdc'
    env(DB_PASSWORD): 'sdc'
    env(MAILER_TRANSPORT): 'smtp'
    env(MAILER_HOST): '127.0.0.1'
    env(MAILER_PORT): '25'
    env(MAILER_USER): null
    env(MAILER_PASSWORD): null
    env(SECRET): 'ThisTokenIsNotSoSecretChangeIt'
    env(DEFAULT_FROM_EMAIL_ADDRESS): 'sdc@opencontent.it'
    env(WKHTMLBINARY): 'wkhtmltopdf'
    env(WKHTMLTOPDF_SERVICE): 'wkhtmltopdf'
    env(EZ_PASSWORD): 'ez'
    env(PITRE_ADAPTER_URL): 'http://localhost:8080/'
    env(HEADER_TOP_TITLE): 'Provincia autonoma di Trento'
    env(HEADER_TOP_LINK): 'http://www.provincia.tn.it/'
    env(FOOTER_CREDITS): 'La <strong>Stanza del cittadino</strong> è una iniziativa progettuale del Consorzio dei Comuni Trentini'
    env(OCSDC_SCHEME): 'https'
    env(OCSDC_HOST): 'devsdc.opencontent.it'
    env(GISCOM_PASSWORD): 'giscom'
    env(GISCOM_ADAPTER_URL): 'https://www.giscom.cloud/WebAPI/'
    env(GISCOM_ADAPTER_USERNAME): 'pippo'
    env(GISCOM_ADAPTER_PASSWORD): 'passw'
    env(PASSWORD_LIFE_TIME): '365'
    env(INACTIVE_USER_LIFE_TIME): '545'
    env(LOGS_PATH): '%kernel.logs_dir%/%kernel.environment%.log'
    env(FORMSERVER_PRIVATE_URL): 'http//formserver'
    env(FORMSERVER_PUBLIC_URL): 'https://formserver.ship.opencontent.io'
    env(HASH_VALIDITY): '1'
