prometheus:
  path: /prometheus.json
  defaults: { _controller: AppBundle:General\Metrics:prometheus}
status:
  path: /php-status
  defaults: { _controller: AppBundle:Ui\Frontend\Default:status}
home:
  path: /
  defaults: { _controller: AppBundle:Ui\Frontend\Default:common }
_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
#home:
#  path:     /{path}
#  defaults: { _controller: AppBundle:Ui\Frontend\Default:common, path: "" }
#  requirements:
#    path: .*

