# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        #in_memory:
            #memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username
        cps:
            id: ocsdc.cps.userprovider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        cps:
            pattern: ^/(pratiche|terms_accept|user)/
            guard:
                provider: cps
                authenticators:
                    - ocsdc.cps.token_authenticator
        operatori:
            anonymous: ~
            pattern: ^/operatori
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
        main:
            anonymous: ~

    access_control:
        - { path: ^/operatori/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/operatori/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/operatori/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/operatori/list, role: ROLE_OPERATORE_ADMIN }
        - { path: ^/operatori, role: ROLE_USER }
        - { path: ^/pratiche, role: ROLE_USER }

    role_hierarchy:
            ROLE_ADMIN:           ROLE_OPERATORE_ADMIN
            ROLE_OPERATORE_ADMIN: ROLE_USER
