# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ocsdc.cps.userprovider:
        class: AppBundle\Services\CPSUserProvider
        arguments: ["@doctrine.orm.default_entity_manager", "@logger"]

    ocsdc.cps.token_authenticator:
        class: AppBundle\Security\CPSAuthenticator

    ocsdc.cps.terms_acceptance_listener:
        class: AppBundle\EventListener\TermsAcceptListener
        arguments: ["@router","@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    gedmo.listener.sluggable:
            class: Gedmo\Sluggable\SluggableListener
            tags:
                - { name: doctrine.event_subscriber, connection: default }
            calls:
                - [ setAnnotationReader, [ "@annotation_reader" ] ]

    monolog_processor:
            class: Monolog\Processor\PsrLogMessageProcessor
            tags:
                - { name: monolog.processor }
