# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ocsdc.cps.userprovider:
        class: AppBundle\Services\CPSUserProvider
        arguments: ["@doctrine.orm.default_entity_manager", "@logger"]

    ocsdc.cps.token_authenticator:
        class: AppBundle\Security\CPSAuthenticator

    ocsdc.cps.terms_acceptance_listener:
        class: AppBundle\EventListener\TermsAcceptListener
        arguments: ["@router","@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    monolog_processor:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor }

    ocsdc.form.flow.type_extension.help_data:
        class: AppBundle\Form\Extension\HelpDataTypeExtension
        arguments: ["@translator"]
        tags:
            - { name: form.type_extension, alias: "form", extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    ocsdc.allegati.directory_namer:
        class: AppBundle\Services\DirectoryNamerService

    ocsdc.allegati.mimetype_validator:
        class: AppBundle\Validator\Constraints\ValidMimeTypeValidator
        arguments: ["@translator"]
        tags:
            - { name: validator.constraint_validator }

    ocsdc.mailer:
        class: AppBundle\Services\MailerService
        arguments: ["@mailer", "@translator", "@templating"]

    ocsdc.modulo_pdf_builder:
        class: AppBundle\Services\ModuloPdfBuilderService
        arguments:
            - "@filesystem"
            - "@doctrine.orm.default_entity_manager"
            - "@translator"
            - "@vich_uploader.property_mapping_factory"
            - "@ocsdc.allegati.directory_namer"
            - "@knp_snappy.pdf"
            - "@templating"

    ocsdc.form.flow.storage_key_generator:
        class: AppBundle\Form\UserSessionStorageKeyGenerator

    ocsdc.form.type.choose_allegato:
        class: AppBundle\Form\Base\ChooseAllegatoType
        arguments: ["@doctrine.orm.entity_manager", "@validator"]
        tags:
            - { name: form.type }
    ocsdc.form.flow.pratica:
        class: AppBundle\Form\Base\PraticaFlow
        parent: craue.form.flow
        arguments: ["@logger","@translator"]

    ocsdc.form.flow.asilonido:
        class: AppBundle\Form\IscrizioneAsiloNido\IscrizioneAsiloNidoFlow
        parent: ocsdc.form.flow.pratica

    ocsdc.form.flow.autoletturaacqua:
        class: AppBundle\Form\AutoletturaAcqua\AutoletturaAcquaFlow
        parent: ocsdc.form.flow.pratica

    ocsdc.form.flow.contributopannolini:
        class: AppBundle\Form\ContributoPannolini\ContributoPannoliniFlow
        parent: ocsdc.form.flow.pratica

    ocsdc.form.flow.cambioresidenza:
        class: AppBundle\Form\CambioResidenza\CambioResidenzaFlow
        parent: ocsdc.form.flow.pratica

    ocsdc.form.flow.allacciamentoacquedotto:
        class: AppBundle\Form\AllacciamentoAcquedotto\AllacciamentoAcquedottoFlow
        parent: ocsdc.form.flow.pratica
        arguments: ["@logger","@translator"]

    ocsdc.form.flow.certificatonascita:
        class: AppBundle\Form\CertificatoNascita\CertificatoNascitaFlow
        parent: ocsdc.form.flow.pratica
        arguments: ["@logger","@translator"]

    ocsdc.form.flow.praticaoperatore:
        class: AppBundle\Form\Operatore\Base\PraticaOperatoreFlow
        parent: craue.form.flow
        arguments: ["@logger","@translator"]

    ocsdc.form.flow.certificatonascitaoperatore:
        class: AppBundle\Form\Operatore\CertificatoNascita\CertificatoNascitaOperatoreFlow
        parent: ocsdc.form.flow.praticaoperatore
        arguments: ["@logger","@translator"]