monolog:
  handlers:
    all_logs:
      type: fingers_crossed
      action_level: info
      handler: stdout
      excluded_http_codes: [404, 405]

    filter_errors:
      type: fingers_crossed
      action_level: error
      handler: sdterr
      excluded_http_codes: [404, 405]

    stdout:
      type: stream
      path: 'php://stdout'
      formatter: monolog.formatter.json
      level: debug

    sdterr:
      type: stream
      path: 'php://stderr'
      formatter: monolog.formatter.json
      level: error

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
