#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $TENANT_DATABASE_DEFAULT_USER WITH PASSWORD '$TENANT_DATABASE_DEFAULT_PASSWORD';
EOSQL
