imports:
    - { resource: ../parameters.yml }
    - { resource: ../common/security.yml }
    - { resource: ../services.yml }
    - { resource: ../bundles/ }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: ../config.yml }


parameters:
    prefix: fondazione-mach
    codice_meccanografico: fem
    database_name: sdc_fem

framework:
    router:
        resource: "%kernel.root_dir%/config/common/routing.yml"
        strict_requirements: true

twig:
    globals:
        endpoint_prefix: '%prefix%'

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            level:        info
            handler:      nested
        nested:
            type:  stream
            path:  "%logs_path%"
            level: info
            action_level: debug
        console:
            type:  console
        slack:
            type:           slackwebhook
            webhook_url:    '%slack_logs_webhook_url%'
            action_level:   error
            level:          error
            formatter: '%logs_formatter%'

services:
    ocsdc.protocollo.handler: "@ocsdc.protocollo.handlers.pitre"
