monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: info
      level:        info
      handler:      nested
    nested:
      type:  stream
      path:  "%logs_path%"
      level: info
      action_level: debug
    console:
      type:  console
