monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: debug
      level:        debug
      handler:      nested
      formatter: "monolog.formatter.line"
    nested:
      type:  stream
      path:  "%logs_path%"
      level: debug
      action_level: debug
      formatter: "monolog.formatter.line"
    console:
      type:  console
