monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: info
      level:        info
      handler:      nested
      formatter: "monolog.formatter.json"
    nested:
      type:  stream
      path:  "%logs_path%"
      level: info
      action_level: info
      formatter: "monolog.formatter.json"
    console:
      type:  console
