app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   "/%prefix%"

api_auth:
    path: "/%prefix%/api/auth"
    methods:  [POST]

rest:
    resource: '@AppBundle/Controller/Rest/'
    type: annotation
    prefix: "/%prefix%/api"

fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: "/%prefix%/operatori"

fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/%prefix%/operatori/profile"

fos_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/%prefix%/operatori/resetting"

fos_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/%prefix%/operatori/profile"

app.swagger_ui:
    path: "/%prefix%/api/doc/{area}"
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }

app.swagger:
    path: "/%prefix%/api/doc.json"
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app_metrics:
  path: "/%prefix%/"
  controller: AppBundle\Controller\DefaultController::metricsAction

