app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   "/%prefix%"

fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: "/%prefix%/operatori"

fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/%prefix%/operatori/profile"

fos_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/%prefix%/operatori/resetting"

fos_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/%prefix%/operatori/change_password"

