<?php declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220728090333 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE ente_asili DROP CONSTRAINT fk_2b51e7092d9f8a53');
        $this->addSql('ALTER TABLE pratica DROP CONSTRAINT fk_448253ac2d9f8a53');
        $this->addSql('DROP TABLE ente_asili');
        $this->addSql('DROP TABLE asilo_nido');
        $this->addSql('DROP INDEX idx_448253ac2d9f8a53');
        $this->addSql('ALTER TABLE pratica DROP asilo_id');
        $this->addSql('ALTER TABLE pratica DROP iban');
        $this->addSql('ALTER TABLE pratica DROP intestatario_conto');
        $this->addSql('ALTER TABLE pratica DROP accetto_utilizzo');
        $this->addSql('ALTER TABLE pratica DROP struttura_orario');
        $this->addSql('ALTER TABLE pratica DROP periodo_iscrizione_da');
        $this->addSql('ALTER TABLE pratica DROP periodo_iscrizione_a');
        $this->addSql('ALTER TABLE pratica DROP bambino_nome');
        $this->addSql('ALTER TABLE pratica DROP bambino_cognome');
        $this->addSql('ALTER TABLE pratica DROP bambino_luogo_nascita');
        $this->addSql('ALTER TABLE pratica DROP bambino_data_nascita');
        $this->addSql('ALTER TABLE pratica DROP intestatario_codice_utente');
        $this->addSql('ALTER TABLE pratica DROP intestatario_nome');
        $this->addSql('ALTER TABLE pratica DROP intestatario_cognome');
        $this->addSql('ALTER TABLE pratica DROP intestatario_indirizzo');
        $this->addSql('ALTER TABLE pratica DROP intestatario_cap');
        $this->addSql('ALTER TABLE pratica DROP intestatario_citta');
        $this->addSql('ALTER TABLE pratica DROP intestatario_telefono');
        $this->addSql('ALTER TABLE pratica DROP intestatario_email');
        $this->addSql('ALTER TABLE pratica DROP contatore_numero');
        $this->addSql('ALTER TABLE pratica DROP contatore_uso');
        $this->addSql('ALTER TABLE pratica DROP contatore_unita_immobiliari');
        $this->addSql('ALTER TABLE pratica DROP lettura_metri_cubi');
        $this->addSql('ALTER TABLE pratica DROP lettura_data');
        $this->addSql('ALTER TABLE pratica DROP note');
        $this->addSql('ALTER TABLE pratica DROP tipo_pannolini');
        $this->addSql('ALTER TABLE pratica DROP nome_punto_vendita');
        $this->addSql('ALTER TABLE pratica DROP data_acquisto');
        $this->addSql('ALTER TABLE pratica DROP totale_spesa');
        $this->addSql('ALTER TABLE pratica DROP provenienza');
        $this->addSql('ALTER TABLE pratica DROP comune_di_provenienza');
        $this->addSql('ALTER TABLE pratica DROP stato_estero_di_provenienza');
        $this->addSql('ALTER TABLE pratica DROP comune_estero_di_provenienza');
        $this->addSql('ALTER TABLE pratica DROP altra_provenienza');
        $this->addSql('ALTER TABLE pratica DROP residenza_provincia');
        $this->addSql('ALTER TABLE pratica DROP residenza_comune');
        $this->addSql('ALTER TABLE pratica DROP residenza_indirizzo');
        $this->addSql('ALTER TABLE pratica DROP residenza_numero_civico');
        $this->addSql('ALTER TABLE pratica DROP residenza_scala');
        $this->addSql('ALTER TABLE pratica DROP residenza_piano');
        $this->addSql('ALTER TABLE pratica DROP residenza_interno');
        $this->addSql('ALTER TABLE pratica DROP persone_residenti');
        $this->addSql('ALTER TABLE pratica DROP tipo_occupazione');
        $this->addSql('ALTER TABLE pratica DROP proprietario_catasto_sezione');
        $this->addSql('ALTER TABLE pratica DROP proprietario_catasto_foglio');
        $this->addSql('ALTER TABLE pratica DROP proprietario_catasto_particella');
        $this->addSql('ALTER TABLE pratica DROP proprietario_catasto_subalterno');
        $this->addSql('ALTER TABLE pratica DROP contratto_agenzia');
        $this->addSql('ALTER TABLE pratica DROP contratto_numero');
        $this->addSql('ALTER TABLE pratica DROP contratto_data');
        $this->addSql('ALTER TABLE pratica DROP usufruttuario_info');
        $this->addSql('ALTER TABLE pratica DROP info_accertamento');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_provincia');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_comune');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_indirizzo');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_numero_civico');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_cap');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_scala');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_piano');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_interno');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_categoria');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_codice_comune');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_foglio');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_sezione');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_mappale');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_catasto_subalterno');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_immobile_qualifica');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_tipo_intervento');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_tipo_allaccio');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_tipo_uso');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_diametro_rete_interna');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_use_alternate_contact');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_alternate_contact_via');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_alternate_contact_civico');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_alternate_contact_cap');
        $this->addSql('ALTER TABLE pratica DROP allacciamento_acquedotto_alternate_contact_comune');
        $this->addSql('ALTER TABLE pratica DROP cf_org_richiedente');
        $this->addSql('ALTER TABLE pratica DROP piva_org_richiedente');
        $this->addSql('ALTER TABLE pratica DROP email_org_richiedente');
        $this->addSql('ALTER TABLE pratica DROP tel_org_richiedente');
        $this->addSql('ALTER TABLE pratica DROP tipologia_attivita');
        $this->addSql('ALTER TABLE pratica DROP uso_contributo');
        $this->addSql('ALTER TABLE pratica DROP descrizione_contributo');
        $this->addSql('ALTER TABLE pratica DROP anno_attivita');
        $this->addSql('ALTER TABLE componente_nucleo_familiare DROP CONSTRAINT fk_67032d0d24038deb');
        $this->addSql('DROP INDEX idx_67032d0d24038deb');
        $this->addSql('ALTER TABLE componente_nucleo_familiare DROP pratica_id');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE ente_asili (ente_id UUID NOT NULL, asilo_id UUID NOT NULL, PRIMARY KEY(ente_id, asilo_id))');
        $this->addSql('CREATE INDEX idx_2b51e7092d9f8a53 ON ente_asili (asilo_id)');
        $this->addSql('CREATE INDEX idx_2b51e709efb68f0a ON ente_asili (ente_id)');
        $this->addSql('CREATE TABLE asilo_nido (id UUID NOT NULL, name VARCHAR(100) NOT NULL, scheda_informativa TEXT DEFAULT NULL, orari TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE ente_asili ADD CONSTRAINT fk_2b51e7092d9f8a53 FOREIGN KEY (asilo_id) REFERENCES asilo_nido (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ente_asili ADD CONSTRAINT fk_2b51e709efb68f0a FOREIGN KEY (ente_id) REFERENCES ente (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE componente_nucleo_familiare ADD pratica_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE componente_nucleo_familiare ADD CONSTRAINT fk_67032d0d24038deb FOREIGN KEY (pratica_id) REFERENCES pratica (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_67032d0d24038deb ON componente_nucleo_familiare (pratica_id)');
        $this->addSql('ALTER TABLE pratica ADD asilo_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD iban VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_conto VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD accetto_utilizzo BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD struttura_orario VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD periodo_iscrizione_da DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD periodo_iscrizione_a DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD bambino_nome VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD bambino_cognome VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD bambino_luogo_nascita VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD bambino_data_nascita DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_codice_utente VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_nome VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_cognome VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_indirizzo VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_cap INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_citta VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_telefono VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD intestatario_email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contatore_numero VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contatore_uso VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contatore_unita_immobiliari VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD lettura_metri_cubi VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD lettura_data DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD tipo_pannolini INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD nome_punto_vendita VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD data_acquisto TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD totale_spesa INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD provenienza VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD comune_di_provenienza VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD stato_estero_di_provenienza VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD comune_estero_di_provenienza VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD altra_provenienza TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_provincia VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_comune VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_indirizzo VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_numero_civico VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_scala VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_piano VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD residenza_interno VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD persone_residenti TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD tipo_occupazione VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD proprietario_catasto_sezione VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD proprietario_catasto_foglio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD proprietario_catasto_particella VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD proprietario_catasto_subalterno VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contratto_agenzia VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contratto_numero VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD contratto_data DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD usufruttuario_info TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD info_accertamento TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_provincia VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_comune VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_indirizzo VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_numero_civico VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_cap VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_scala VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_piano VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_interno VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_categoria VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_codice_comune VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_foglio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_sezione VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_mappale VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_catasto_subalterno VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_immobile_qualifica VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_tipo_intervento VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_tipo_allaccio VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_tipo_uso VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_diametro_rete_interna VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_use_alternate_contact BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_alternate_contact_via VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_alternate_contact_civico VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_alternate_contact_cap VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD allacciamento_acquedotto_alternate_contact_comune VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD cf_org_richiedente VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD piva_org_richiedente VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD email_org_richiedente VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD tel_org_richiedente VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD tipologia_attivita VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD uso_contributo VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD descrizione_contributo TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD anno_attivita VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pratica ADD CONSTRAINT fk_448253ac2d9f8a53 FOREIGN KEY (asilo_id) REFERENCES asilo_nido (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_448253ac2d9f8a53 ON pratica (asilo_id)');
    }
}
