monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            level:        info
            handler:      nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type:  stream
            path:  "%logs_path%"
            level: info
            action_level: debug
        console:
            type:  console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        #slack:
        #  type:           slackwebhook
        #  webhook_url:    '%slack_logs_webhook_url%'
        #  action_level:   error
        #  level:          error
        #  formatter: '%logs_formatter%'
