monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: info
      handler:      nested
      excluded_http_codes: [ 404, 405 ]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
    nested:
      type:  stream
      path:  "%logs_path%"
    console:
      type:  console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine" ]
