monolog:
  handlers:
    all_logs:
      type: fingers_crossed
      action_level: info
      handler: filter_stdout
      excluded_http_codes: [404, 405]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      channels: ["!php"]

    filter_errors:
      type: fingers_crossed
      action_level: error
      handler: sdterr
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      excluded_http_codes: [404, 405]

    filter_stdout:
      type: filter
      min_level: info
      max_level: warning
      handler: stdout

    stdout:
      type: stream
      path: 'php://stdout'
      formatter: monolog.formatter.json
      level: info

    sdterr:
      type: stream
      path: 'php://stderr'
      formatter: monolog.formatter.json
      level: error

    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]

