paths:
#defaults
  - uri: stanzadelcittadino.localtest.me
    path: comune-di-bugliano
    instance: comune-di-bugliano

instances:
  comune-di-bugliano:
    codice_meccanografico: c_cbug
    database_name: sdc_bugliano
    login_route: login_open
    single_logout_url: 'http://auth.localtest.me/slo?redirect=http://stanzadelcittadino.localtest.me/comune-di-bugliano/'
    protocollo: dummy
