instances:
  stanzadelcittadino.localtest.me/comune-di-bugliano:
    codice_meccanografico: c_cbug
    identifier: comune-di-bugliano
    login_route: login_pat
    protocollo: dummy
    database_name: sdc_bugliano_online
