# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  prefix: '%env(PREFIX)%'
  instance: ''
  protocollo: ''
  database_driver: '%env(DB_DRIVER)%'
  database_host: '%env(DB_HOST)%'
  database_port: '%env(DB_PORT)%'
  database_name: '%env(DB_NAME)%'
  database_user: '%env(DB_USER)%'
  database_password: '%env(DB_PASSWORD)%'
  database_reconnect_attemps: '%env(DB_RECONNECT_ATTEMPS)%'
  mailer_transport: '%env(MAILER_TRANSPORT)%'
  mailer_host: '%env(MAILER_HOST)%'
  mailer_port: '%env(MAILER_PORT)%'
  mailer_user: '%env(MAILER_USER)%'
  mailer_password: '%env(MAILER_PASSWORD)%'
  mailer_encription: 'tls'
  pec_mailer_transport: '%env(PEC_MAILER_TRANSPORT)%'
  pec_mailer_host: '%env(PEC_MAILER_HOST)%'
  pec_mailer_port: '%env(PEC_MAILER_PORT)%'
  pec_mailer_user: '%env(PEC_MAILER_USER)%'
  pec_mailer_password: '%env(PEC_MAILER_PASSWORD)%'
  pec_delivery_address: '%env(PEC_DELIVERY_ADDRESS)%'
  secret: '%env(SECRET)%'
  default_from_email_address: '%env(DEFAULT_FROM_EMAIL_ADDRESS)%'
  wkhtmlbinary: '%env(WKHTMLBINARY)%'
  wkhtmltopdf_service: '%env(WKHTMLTOPDF_SERVICE)%'
  ez_password: '%env(EZ_PASSWORD)%'
  pitre_adapter_url: '%env(PITRE_ADAPTER_URL)%'
  header_top_title: '%env(HEADER_TOP_TITLE)%'
  header_top_link: '%env(HEADER_TOP_LINK)%'
  footer_credits: '%env(FOOTER_CREDITS)%'
  ocsdc_iter_duration_start_status: 3
  ocsdc_iter_duration_end_statuses:
    - 10
    - 100
  ocsdc_default_date_format: 'd-m-Y'
  ocsdc_default_datetime_format: 'd-m-Y H:i:s'
  ocsdc_default_time_format: 'H:i:s'
  ocsdc_scheme: '%env(OCSDC_SCHEME)%'
  ocsdc_host: '%env(OCSDC_HOST)%'
  giscom_password: '%env(GISCOM_PASSWORD)%'
  giscom_adapter_url: '%env(GISCOM_ADAPTER_URL)%'
  giscom_adapter_username: '%env(GISCOM_ADAPTER_USERNAME)%'
  giscom_adapter_password: '%env(GISCOM_ADAPTER_PASSWORD)%'
  generate_p7m_thumbnail: true
  gsbinary: gs
  ocsdc_default_moment_datetime_format: 'DD-MM-YYYY HH:mm:ss'
  mypay_adapter_url: '%env(MYPAY_ADAPTER_URL)%'
  ocsdc_slim_datetime_format: 'd/m/y H:i'
  PasswordLifeTime: '%env(PASSWORD_LIFE_TIME)%' #365
  InactiveUserLifeTime: '%env(INACTIVE_USER_LIFE_TIME)%' #545
  logs_formatter: 'monolog.formatter.line'
  logs_path: '%env(LOGS_PATH)%'
  formserver_private_url: '%env(FORMSERVER_PRIVATE_URL)%'
  formserver_public_url: '%env(FORMSERVER_PUBLIC_URL)%'
  formserver_admin_url: '%env(FORMSERVER_ADMIN_URL)%'
  hash_validity: '%env(HASH_VALIDITY)%'
  allowed_extensions:
    - doc: application/msword
    - docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - odt: application/vnd.oasis.opendocument.text
    - pdf: application/pdf
    - txt: text/plain
    - jpeg: image/jpeg
    - jpg: image/jpeg
    - png: image/png
    - gif: image/gif
    - p7m: application/pkcs7-mime
    - xp7m: application/x-pkcs7-mime
    - p7c: application/pkcs7
    - zip: application/zip
  token_ttl: '%env(TOKEN_TTL)%'
  recaptcha_key: '%env(RECAPTCHA_KEY)%'
  recaptcha_secret: '%env(RECAPTCHA_SECRET)%'
  shibbolet_server_varnames:
    codiceFiscale: '%env(SHIB_CODICEFISCALE)%'
    capDomicilio: '%env(SHIB_CAPDOMICILIO)%'
    capResidenza: '%env(SHIB_CAPRESIDENZA)%'
    cellulare: '%env(SHIB_CELLULARE)%'
    cittaDomicilio: '%env(SHIB_CITTADOMICILIO)%'
    cittaResidenza: '%env(SHIB_CITTARESIDENZA)%'
    cognome: '%env(SHIB_COGNOME)%'
    dataNascita: '%env(SHIB_DATANASCITA)%'
    emailAddress: '%env(SHIB_EMAILADDRESS)%'
    emailAddressPersonale: '%env(SHIB_EMAILADDRESSPERSONALE)%'
    indirizzoDomicilio: '%env(SHIB_INDIRIZZODOMICILIO)%'
    indirizzoResidenza: '%env(SHIB_INDIRIZZORESIDENZA)%'
    luogoNascita: '%env(SHIB_LUOGONASCITA)%'
    nome: '%env(SHIB_NOME)%'
    provinciaDomicilio: '%env(SHIB_PROVINCIADOMICILIO)%'
    provinciaNascita: '%env(SHIB_PROVINCIANASCITA)%'
    provinciaResidenza: '%env(SHIB_PROVINCIARESIDENZA)%'
    sesso: '%env(SHIB_SESSO)%'
    statoDomicilio: '%env(SHIB_STATODOMICILIO)%'
    statoNascita: '%env(SHIB_STATONASCITA)%'
    statoResidenza: '%env(SHIB_STATORESIDENZA)%'
    telefono: '%env(SHIB_TELEFONO)%'
    titolo: '%env(SHIB_TITOLO)%'
    idCard: '%env(SHIB_IDCARD)'
    x509certificate_issuerdn: '%env(SHIB_X509CERTIFICATE_ISSUERDN)%'
    x509certificate_subjectdn: '%env(SHIB_X509CERTIFICATE_SUBJECTDN)%'
    x509certificate_base64: '%env(SHIB_X509CERTIFICATE_BASE64)%'
    spidCode: '%env(SHIB_SPID_CODE)%'
    shibSessionId: '%env(SHIB_SESSION_ID)%'
    shibSessionIndex: '%env(SHIB_SESSION_INDEX)%'
    shibAuthenticationIstant: '%env(SHIB_AUTHENTICATION_INSTANT)%'
    shibAuthnContextClass: '%env(SHIB_AUTHN_CONTEXT_CLASS)%'
  sentry_dsn: '%env(SENTRY_DSN)%'
  login_route: '%env(LOGIN_ROUTE)%' #name of the route
  single_logout_url: '%env(SINGLE_LOGOUT_URL)%'
  browsers_restrictions: '%env(BROWSERS_RESTRICTIONS)%'
  io_api_url: '%env(IO_API_URL)%'
  cache_max_age: '%env(CACHE_MAX_AGE)%'
  metrics_type: '%env(METRICS_TYPE)%'
  metrics_redis_host: '%env(METRICS_REDIS_HOST)%'
  metrics_redis_port: 6379 #se passato con variabile da errore sul tipo, risolto in sf4
  metrics_redis_password: '%env(METRICS_REDIS_PASSWORD)%'
  upload_destination: '%env(UPLOAD_DESTINATION)%'
  s3_region: '%env(S3_REGION)%'
  s3_key: '%env(S3_KEY)%'
  s3_secret: '%env(S3_SECRET)%'
  s3_bucket: '%env(S3_BUCKET)%'
  deda_login_client_id: 'example'
  deda_login_secret: 'example'
  deda_login_env: 'prod'
  kafka_url: '%env(KAFKA_URL)%'
  ksqldb_url: '%env(KSQLDB_URL)%'
  kafka_event_version: '%env(KAFKA_EVENT_VERSION)%'
  kafka_request_timeout: '%env(KAFKA_REQUEST_TIMEOUT)%'
  kafka_topics:
    applications: '%env(KAFKA_TOPIC_APPLICATIONS)%'
    services: '%env(KAFKA_TOPIC_SERVICES)%'
    meetings: '%env(KAFKA_TOPIC_MEETINGS)%'
    calendars: '%env(KAFKA_TOPIC_CALENDARS)%'
  api_version: 1
  cas_login_url: 'https://mycasserver/cas/'
  cas_validation_url: 'https://mycasserver/cas/serviceValidate'
  # Payment gateways
  payment_gateways:
    bollo:
      name: Bollo
      url: null
      handler: bollo # <-- identificativo dell'handler che gestisce il pagamento
      enabled: true
    efil:
      name: Efil
      url: efil.gateway.opencontent.io
      handler: generic-external
      enabled: true
    mypay:
      name: Mypay
      url: mypay.gateway.opencontent.io
      handler: mypay
      enabled: true
  analytics:
    plan: '%env(ANALYTICS_PLAN)%'
  google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    bind: # defines the scalar arguments once and apply them to any service defined/created in this file
      $defaultApiVersion: '%api_version%'
      $locales: '%app_locales%'
      $defaultSender: '%default_from_email_address%'
      $allowedExtensions: '%allowed_extensions%'
      $hashValidity: '%hash_validity%'


  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  ## Stanzadelcittadino

  App\EventListener\MeetingLifeCycleListener:
    tags:
      - { name: doctrine.event_listener, event: postPersist, connection: default }
      - { name: doctrine.event_listener, event: preUpdate, connection: default }
      - { name: doctrine.event_listener, event: postRemove, connection: default }

  App\Controller\Rest\DocumentsAPIController:
    arguments:
      $rootDir: '%kernel.root_dir%'


